print("installing python user")
print("loading...")
print("loading...")
print("loading...")
print("             ")
print("(\ _ /)")
print("( 'x' )")
print(" c()()")
print("python bunny")
print("             ")
print("welcome kushi")
